// Import modules
const fs = require('fs')
const https = require('https')
const express = require('express')
const {
	MessageHub,
	PlatformDiscord,
	PlatformMessenger
} = require('../')

// Set up variables
let port = 8080
// Retrieve tokens
const messengerToken = ''
const messengerVerificationToken = ''

const discordToken = ''
const discordClientID = ''

// If using HTTPS (required by Facebook Messenger)
const sslKeyPath = ''
const sslCertPath = ''
if(sslKeyPath && sslCertPath)
	port = 443 // Default HTTPS port

// Set up message hub and add platforms
let messageHub = new MessageHub()

if(messengerToken && messengerVerificationToken)
{
	let options = {}
	options.debug = true
	options.token = messengerToken
	options.verificationToken = messengerVerificationToken

	let platformMessenger = new PlatformMessenger(options)
	messageHub.addPlatform(platformMessenger)
}

if(discordToken)
{
	let options = {}
	options.debug = true
	options.token = discordToken
	options.clientID = discordClientID

	let platformDiscord = new PlatformDiscord(options)
	messageHub.addPlatform(platformDiscord)
}

// Set up callback for when message is received
messageHub.on('message', (msg) =>
{
	/*
	msg : HubMessage
		hub			: MessageHub - The hub that instantiated the message
		platform	: string	 - Platform used to receive this message
		user		: number	 - User ID of sender
		content		: string	 - Textual contents
		additional	: object	 - Object containing contents specific to platform
			e.g. DiscordChannel for discord
	*/
	msg.reply('Echo: ' + msg.text)
})

// Set up express app
const app = express()
// use paths generated by the hub, but prepend /platforms/ first
//	e.g. http://localhost:8080/platforms/facebook_messenger
app.use('/platforms', messageHub.router)

if(sslKeyPath && sslCertPath)
{
	let secureOptions = {}
	secureOptions.key = fs.readFileSync(sslKeyPath)
	secureOptions.cert = fs.readFileSync(sslCertPath)
	https.createServer(secureOptions, app)
			.listen(port, function() { console.log('Listening on port ' + port) })
}
else
{
	app.listen(port, function() { console.log('Listening on port ' + port) })
}
